const items = [
  {
    id: 1,
    date: '2025년 3월 7일 (금)',
    name: '지거 경계선 위의 우리 시리즈',
    EngName: 'Zsiga Borderline Drifter Series',
    comp1: '지거 경계선 위의 우리 시리즈 휴대폰 스트랩',
    comp1Eng: 'Zsiga Borderline Drifter Series Phone Charm',
    comp2: '지거 경계선 위의 우리 시리즈 삼각 백',
    comp2Eng: 'Zsiga Borderline Drifter Series Triangular Bag',
    comp3: '지거 경계선 위의 우리 시리즈 숄더 백',
    comp3Eng: 'Zsiga Borderline Drifter Series Shoulder Bag',
    comp4: '바비 스타일 아이콘 시리즈',
    comp4Eng: 'Barbie Style Icon Series',
  },
  {
    id: 2,
    date: '2025년 3월 12일 (수)',
    name: '베이비 몰리 껌딱지 시리즈 시리즈',
    EngName: 'Baby Molly My Huggable Discovery Series',
    comp1: '잔망루피의 포스팅 시리즈',
    comp1Eng: `ZANMANG LOOPY's Moments Series`,
    comp2: '하치푸푸 동물들과 함께 시리즈',
    comp2Eng: 'HACIPUPU Sunggle With You Series',
    comp3: '몰리의 데일리 룩 시리즈 에어팟 프로 케이스',
    comp3Eng: 'MOLLY Daily Look Series Earchone Case for Airpods Pro',
    comp4: '몰리의 데일리 룩 시리즈 - 카드홀더',
    comp4Eng: 'MOLLY Daily Look Series Cardholder Pendant',
  },
];
