export const items = [
  {
    id: 1,
    date: '2025. 3. 7 (금)',
    name: '지거 경계선 위의 우리 시리즈',
    EngName: 'Zsiga Borderline Drifter Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice0/notice0.png?raw=true',
    comp1: '지거 경계선 위의 <br>우리 시리즈 휴대폰 스트랩',
    comp1Eng: 'Zsiga Borderline Drifter Series Phone Charm',
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice0/notice0-1.png?raw=true',
    comp2: '지거 경계선 위의<br>우리 시리즈 삼각 백',
    comp2Eng: 'Zsiga Borderline Drifter Series Triangular Bag',
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice0/notice0-2.png?raw=true',
    comp3: '지거 경계선 위의 <br>우리 시리즈 숄더 백',
    comp3Eng: 'Zsiga Borderline Drifter Series Shoulder Bag',
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice0/notice0-3.png?raw=true',
    comp4: '바비 스타일 아이콘 시리즈',
    comp4Eng: 'Barbie Style Icon Series',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice0/notice0-4.png?raw=true',
  },
  {
    id: 2,
    date: '2025. 3. 12 (수)',
    name: '베이비 몰리 껌딱지 시리즈',
    EngName: 'Baby Molly My Huggable Discovery Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice01/notice01.png?raw=true',
    comp1: '잔망루피의 포스팅 시리즈',
    comp1Eng: `ZANMANG LOOPY's Moments Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice01/notice01-2.png?raw=true',
    comp2: '하치푸푸 동물들과 함께 시리즈',
    comp2Eng: 'HACIPUPU Sunggle With You Series',
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice01/notice01-3.png?raw=true',
    comp3: '몰리의 데일리 룩 시리즈 <br>에어팟 프로 케이스',
    comp3Eng: 'MOLLY Daily Look Series Earchone Case for Airpods Pro',
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice01/notice01-4.png?raw=true',
    comp4: '몰리의 데일리 룩 시리즈 - 카드홀더',
    comp4Eng: 'MOLLY Daily Look Series Cardholder Pendant',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice01/notice01-5.png?raw=true',
  },
  {
    id: 3,
    date: '2025. 3. 16. (일)',
    name: '스위트빈 안아줘 시리즈',
    EngName: 'Sweet Bean I Want a Hug Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice02/notice02.png?raw=true',
    comp1: 'THE MONSTERS 체크메이트 시리즈 인형',
    comp1Eng: `THE MONSTERS Let's Checkmate Series Vinyl Plush Doll`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice02/notice02-2.png?raw=true',
    comp2: 'THE MONSTERS 체크메이트 시리즈 <br>인형 키링',
    comp2Eng: `THE MONSTERS Let's Checkmate Series Vinyl Plush Blister`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice02/notice02-3.png?raw=true',
    comp3: 'THE MONSTERS 체크메이트 시리즈 <br>데스크 매트',
    comp3Eng: `THE MONSTERS Let's Checkmate Series Computer Desk Mat`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice02/notice02-4.png?raw=true',
  },
  {
    id: 4,
    date: '2025. 2. 28 (금)',
    name: '피치 라이엇 러시 아워 시리즈',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice03/notice03.png?raw=true',
    EngName: 'Peacg Riot Rush Hour Series',
    comp1: '스파이더맨 어크로스 더 유니버스 시리즈',
    comp1Eng: `Disney Marvel Spider-Man<br>Across the Spider-Verse Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice03/notice03-2.png?raw=true',
    comp2: '피치 라이엇<br>러시 아워 시리즈 키링',
    comp2Eng: `Peach Riot Rush Hour Series Pendant`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice03/notice03-3.png?raw=true',
    comp3: '피치 라이엇<br>러시 아워 시리즈 마그넷',
    comp3Eng: `Peach Riot Rush Hour Series Fridge Magnet`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice03/notice03-4.png?raw=true',
    comp4: '피치 라이엇<br>러시 아워 시리즈 노트',
    comp4Eng: `Peach Riot Rush Hour Series Notebook`,
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice03/notice03-5.png?raw=true',
  },
  {
    id: 5,
    date: '2025. 2. 26. (수)',
    name: 'THE MONSTERS x 원피스 시리즈',
    EngName: 'THE MONSTERS x One Piece Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice04/notice04.png?raw=true',
    comp1: '디즈니 미키 패밀리 <br>언제나 함께 인형 키링',
    comp1Eng: `Disney Mickey Family Cute Together Keychain Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice04/notice04-2.png?raw=true',
    comp2: '메가 로얄 몰리 모네 수련 400%',
    comp2Eng: `MEGA ROYAL MOLLY 400% Monet-Les Nympheas`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice04/notice04-3.png?raw=true',
    comp3: '스폰지밥 백팩',
    comp3Eng: 'SpongeBob Backpack',
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice04/notice04-4.png?raw=true',
    comp4: '스폰지밥 비키니 시티 스마트톡',
    comp4Eng: 'SpongeBob Bikini Bottom Cell Phone Holder',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice04/notice04-5.png?raw=true',
  },
  {
    id: 6,
    date: '2025. 3. 18. (월)',
    name: '라부부 코카콜라 시리즈 인형 키링',
    EngName: 'THE MONSTERS COCA-COLA SERIES Vinyl Face',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice04/notice04.png?raw=true',
    comp1: '디무 차 한 잔의 여유 시리즈',
    comp1Eng: `DIMOO Stories in the Cup Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice04/notice04-2.png?raw=true',
    comp2: '디무 차 한 잔의 여유 시리즈 <br>스트랩',
    comp2Eng: `DIMOO Stories in the Cup Series Beaded Pendant`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice04/notice04-3.png?raw=true',
    comp3: '히로노 X CLOT 시리즈<br> (기프트 박스 에디션)',
    comp3Eng: `Hirono x CLOT Series (Gift Box Edition)`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice04/notice04-4.png?raw=true',
    comp4: '메가 스페이스 몰리 X CHEN FENWAN 1000%',
    comp4Eng: 'MEGA SPACE MOLLY 1000% CHEN FENWAN',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice04/notice04-5.png?raw=true',
  },
  {
    id: 7,
    date: '2025. 3. 21. (금)',
    name: '미니 피치 라이엇 로딩! 시리즈',
    EngName: 'Lil Peach Riot Loading! Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice05/notice05.png?raw=true',
    comp1: '미니 피치 라이엇 로딩! 시리즈 뱃지',
    comp1Eng: `Lil Peach Riot Loading! Series Pin`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice05/notice05-2.png?raw=true',
    comp2: '미니 피치 라이엇 로딩! 시리즈 키링',
    comp2Eng: `Lil Peach Riot Loading! Series Keychain`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice05/notice05-3.png?raw=true',
    comp3: '미니 피치 라이엇 로딩! 시리즈 카드 홀더',
    comp3Eng: `Lil Peach Riot Loading! Series Card Holder`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice05/notice05-4.png?raw=true',
    comp4: '하치푸푸 눈사람 BJD',
    comp4Eng: 'HACIPUPU Snowman is Coming BJD',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice05/notice05-5.png?raw=true',
  },
  {
    id: 8,
    date: '2025. 3. 22. (토)',
    name: '피노젤리 아이돌 프로젝트 시리즈',
    EngName: 'PINO JELLY Star Project Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06.png?raw=true',
    comp1: '스위트빈의 과일 세계 모험 시리즈',
    comp1Eng: `Sweet Bean Fruit World Adventure Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-2.png?raw=true',
    comp2: '피노젤리 생일파티 빅 피규어',
    comp2Eng: `PINO JELLY Birthday Bash Big`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-3.png?raw=true',
    comp3: '피노젤리 난 누구게? 블리스터',
    comp3Eng: `PINO JELLY Guess Who I am Blister`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-4.png?raw=true',
    comp4: '스위트빈 잠들기 전 블리스터',
    comp4Eng: 'Sweet Bean Badtime Story Blister',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-5.png?raw=true',
  },
  {
    id: 8,
    date: '2025. 3. 22. (토)',
    name: '스컬판다 소원을 말해봐 시리즈',
    EngName: 'PINO JELLY Star Project Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06.png?raw=true',
    comp1: '스위트빈의 과일 세계 모험 시리즈',
    comp1Eng: `Sweet Bean Fruit World Adventure Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-2.png?raw=true',
    comp2: '피노젤리 생일파티 빅 피규어',
    comp2Eng: `PINO JELLY Birthday Bash Big`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-3.png?raw=true',
    comp3: '피노젤리 난 누구게? 블리스터',
    comp3Eng: `PINO JELLY Guess Who I am Blister`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-4.png?raw=true',
    comp4: '스위트빈 잠들기 전 블리스터',
    comp4Eng: 'Sweet Bean Badtime Story Blister',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-5.png?raw=true',
  },
  {
    id: 8,
    date: '2025. 3. 22. (토)',
    name: '피노젤리 아이돌 프로젝트 시리즈',
    EngName: 'PINO JELLY Star Project Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06.png?raw=true',
    comp1: '스위트빈의 과일 세계 모험 시리즈',
    comp1Eng: `Sweet Bean Fruit World Adventure Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-2.png?raw=true',
    comp2: '피노젤리 생일파티 빅 피규어',
    comp2Eng: `PINO JELLY Birthday Bash Big`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-3.png?raw=true',
    comp3: '피노젤리 난 누구게? 블리스터',
    comp3Eng: `PINO JELLY Guess Who I am Blister`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-4.png?raw=true',
    comp4: '스위트빈 잠들기 전 블리스터',
    comp4Eng: 'Sweet Bean Badtime Story Blister',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-5.png?raw=true',
  },
  {
    id: 8,
    date: '2025. 3. 22. (토)',
    name: '아주라 포근한 봄 시리즈',
    EngName: 'PINO JELLY Star Project Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06.png?raw=true',
    comp1: '스위트빈의 과일 세계 모험 시리즈',
    comp1Eng: `Sweet Bean Fruit World Adventure Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-2.png?raw=true',
    comp2: '피노젤리 생일파티 빅 피규어',
    comp2Eng: `PINO JELLY Birthday Bash Big`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-3.png?raw=true',
    comp3: '피노젤리 난 누구게? 블리스터',
    comp3Eng: `PINO JELLY Guess Who I am Blister`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-4.png?raw=true',
    comp4: '스위트빈 잠들기 전 블리스터',
    comp4Eng: 'Sweet Bean Badtime Story Blister',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-5.png?raw=true',
  },
  {
    id: 8,
    date: '2025. 3. 22. (토)',
    name: '모코코를 찾아라 시리즈',
    EngName: 'PINO JELLY Star Project Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06.png?raw=true',
    comp1: '스위트빈의 과일 세계 모험 시리즈',
    comp1Eng: `Sweet Bean Fruit World Adventure Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-2.png?raw=true',
    comp2: '피노젤리 생일파티 빅 피규어',
    comp2Eng: `PINO JELLY Birthday Bash Big`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-3.png?raw=true',
    comp3: '피노젤리 난 누구게? 블리스터',
    comp3Eng: `PINO JELLY Guess Who I am Blister`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-4.png?raw=true',
    comp4: '스위트빈 잠들기 전 블리스터',
    comp4Eng: 'Sweet Bean Badtime Story Blister',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-5.png?raw=true',
  },
  {
    id: 8,
    date: '2025. 3. 22. (토)',
    name: '작은 별이 보내는 선물 시리즈',
    EngName: 'PINO JELLY Star Project Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06.png?raw=true',
    comp1: '스위트빈의 과일 세계 모험 시리즈',
    comp1Eng: `Sweet Bean Fruit World Adventure Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-2.png?raw=true',
    comp2: '피노젤리 생일파티 빅 피규어',
    comp2Eng: `PINO JELLY Birthday Bash Big`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-3.png?raw=true',
    comp3: '피노젤리 난 누구게? 블리스터',
    comp3Eng: `PINO JELLY Guess Who I am Blister`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-4.png?raw=true',
    comp4: '스위트빈 잠들기 전 블리스터',
    comp4Eng: 'Sweet Bean Badtime Story Blister',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-5.png?raw=true',
  },
  {
    id: 8,
    date: '2025. 3. 29. (수)',
    name: '창문 속 지거 시리즈 세트',
    EngName: 'PINO JELLY Star Project Series',
    mainImg: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06.png?raw=true',
    comp1: '스위트빈의 과일 세계 모험 시리즈',
    comp1Eng: `Sweet Bean Fruit World Adventure Series`,
    comp1Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-2.png?raw=true',
    comp2: '피노젤리 생일파티 빅 피규어',
    comp2Eng: `PINO JELLY Birthday Bash Big`,
    comp2Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-3.png?raw=true',
    comp3: '피노젤리 난 누구게? 블리스터',
    comp3Eng: `PINO JELLY Guess Who I am Blister`,
    comp3Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-4.png?raw=true',
    comp4: '스위트빈 잠들기 전 블리스터',
    comp4Eng: 'Sweet Bean Badtime Story Blister',
    comp4Img: 'https://github.com/hyeonky/dp-static/blob/main/popmart/event/notice/notice06/notice06-5.png?raw=true',
  },
];
