export const items = [
  {
    id: 1,
    date: '2025. 3. 7 (금)',
    name: '지거 경계선 위의 우리 시리즈',
    EngName: 'Zsiga Borderline Drifter Series',
    mainImg: '',
    comp1: '지거 경계선 위의 우리 시리즈 휴대폰 스트랩',
    comp1Eng: 'Zsiga Borderline Drifter Series Phone Charm',
    comp2: '지거 경계선 위의 우리 시리즈 삼각 백',
    comp2Eng: 'Zsiga Borderline Drifter Series Triangular Bag',
    comp3: '지거 경계선 위의 우리 시리즈 숄더 백',
    comp3Eng: 'Zsiga Borderline Drifter Series Shoulder Bag',
    comp4: '바비 스타일 아이콘 시리즈',
    comp4Eng: 'Barbie Style Icon Series',
  },
  {
    id: 2,
    date: '2025. 3. 12 (수)',
    name: '베이비 몰리 껌딱지 시리즈 시리즈',
    EngName: 'Baby Molly My Huggable Discovery Series',
    comp1: '잔망루피의 포스팅 시리즈',
    comp1Eng: `ZANMANG LOOPY's Moments Series`,
    comp2: '하치푸푸 동물들과 함께 시리즈',
    comp2Eng: 'HACIPUPU Sunggle With You Series',
    comp3: '몰리의 데일리 룩 시리즈 에어팟 프로 케이스',
    comp3Eng: 'MOLLY Daily Look Series Earchone Case for Airpods Pro',
    comp4: '몰리의 데일리 룩 시리즈 - 카드홀더',
    comp4Eng: 'MOLLY Daily Look Series Cardholder Pendant',
  },
  {
    id: 3,
    date: '2025. 3. 16. (일)',
    name: '스위트빈 안아줘 시리즈',
    EngName: 'Sweet Bean I Want a Hug Series',
    comp1: 'THE MONSTERS 체크메이트 시리즈 인형',
    comp1Eng: `THE MONSTERS Let's Checkmate Series Vinyl Plush Doll`,
    comp2: 'THE MONSTERS 체크메이트 시리즈 인형 키링',
    comp2Eng: `THE MONSTERS Let's Checkmate Series Vinyl Plush Blister`,
    comp3: 'THE MONSTERS 체크메이트 시리즈 데스크 매트',
    comp3Eng: `THE MONSTERS Let's Checkmate Series Computer Desk Mat`,
  },
  {
    id: 4,
    date: '2025. 2. 28 (금)',
    name: '피치 라이엇 러시 아워 시리즈',
    EngName: 'Peacg Riot Rush Hour Series',
    comp1: '디즈니 스파이더맨 어크로스 더 유니버스 시리즈',
    comp1Eng: `Disney Marvel Spider-Man Across the Spider-Verse Series`,
    comp2: '피치 라이엇 러시 아워 시리즈 키링',
    comp2Eng: `Peach Riot Rush Hour Series Pendant`,
    comp3: '피치 라이엇 러시 아워 시리즈 마그넷',
    comp3Eng: `Peach Riot Rush Hour Series Fridge Magnet`,
    comp4: '피치 라이엇 러시 아워 시리즈 노트',
    comp4Eng: `Peach Riot Rush Hour Series Notebook`,
  },
  {
    id: 5,
    date: '2025. 2. 26. (수)',
    name: 'THE MONSTERS x 원피스 시리즈',
    EngName: 'THE MONSTERS x One Piece Series',
    comp1: '디즈니 미키 패밀리 언제나 함께 시리즈 인형 키링',
    comp1Eng: `Disney Mickey Family Cute Together Keychain Series`,
    comp2: '메가 로얄 몰리 모네 수련 400%',
    comp2Eng: `MEGA ROYAL MOLLY 400% Monet-Les Nympheas`,
    comp3: '스폰지밥 백팩',
    comp3Eng: `SpongeBob Backpack`,
    comp4: '스폰지밥 비키니 시티 스마트톡',
    comp4Eng: 'SpongeBob Bikini Bottom Cell Phone Holder',
  },
  {
    id: 6,
    date: '2025. 3. 18. (월)',
    name: '라부부 코카콜라 시리즈 인형 키링',
    EngName: 'THE MONSTERS COCA-COLA SERIES Vinyl Face',
    comp1: '디무 차 한 잔의 여유 시리즈',
    comp1Eng: `DIMOO Stories in the Cup Series`,
    comp2: '디무 차 한 잔의 여유 시리즈 스트랩',
    comp2Eng: `DIMOO Stories in the Cup Series Beaded Pendant`,
    comp3: '히로노 X CLOT 시리즈 (기프트 박스 에디션)',
    comp3Eng: `Hirono x CLOT Series (Gift Box Edition)`,
    comp4: '메가 스페이스 몰리 X CHEN FENWAN 1000%',
    comp4Eng: 'MEGA SPACE MOLLY 1000% CHEN FENWAN',
  },
  {
    id: 7,
    date: '2025. 3. 21. (금)',
    name: '미니 피치 라이엇 로딩! 시리즈',
    EngName: 'Lil Peach Riot Loading! Series',
    comp1: '미니 피치 라이엇 로딩! 시리즈 뱃지',
    comp1Eng: `Lil Peach Riot Loading! Series Pin`,
    comp2: '미니 피치 라이엇 로딩! 시리즈 키링',
    comp2Eng: `Lil Peach Riot Loading! Series Keychain`,
    comp3: '미니 피치 라이엇 로딩! 시리즈 카드 홀더',
    comp3Eng: `Lil Peach Riot Loading! Series Card Holder`,
    comp4: '하치푸푸 눈사람 BJD',
    comp4Eng: 'HACIPUPU Snowman is Coming BJD',
  },
  {
    id: 8,
    date: '2025. 3. 22. (토)',
    name: '피노젤리 아이돌 프로젝트 시리즈',
    EngName: 'PINO JELLY Star Project Series',
    comp1: '스위트빈의 과일 세계 모험 시리즈',
    comp1Eng: `Sweet Bean Fruit World Adventure Series`,
    comp2: '피노젤리 생일파티 빅 피규어',
    comp2Eng: `PINO JELLY Birthday Bash Big`,
    comp3: '피노젤리 난 누구게? 블리스터',
    comp3Eng: `PINO JELLY Guess Who I am Blister`,
    comp4: '스위트빈 잠들기 전 블리스터',
    comp4Eng: 'Sweet Bean Badtime Story Blister',
  },
];
