const productDetailItem = [
    {
        id: 1,
        title: '라부부 코카콜라 시리즈',
        price: '15,000원',
        mainImages: [
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg2/bigImg2-4.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg2/bigImg2-5.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg2/bigImg2-2.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg2/bigImg2-3.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg2/bigImg2-6.jpg?raw=true',
        ],
        detailImages: [
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail2/detail2.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail2/detail2-2.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail2/detail2-3.jpg?raw=true',
        ],
        information: {
            상품명: '라부부 코카콜라 시리즈',
            브랜드: 'POP MART',
            사용연령: '15세 이상',
            사이즈: '77 ~ 107mm',
            재질: 'PVC / ABS',
        },
    },
    {
        id: 2,
        title: '스컬판다 소리 시리즈',
        price: '15,000원',
        mainImages: [
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg4/bigImg4.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg4/bigImg4-3.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg4/bigImg4-10.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg4/bigImg4-2.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg4/bigImg4-9.jpg?raw=true',
        ],
        detailImages: [
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail4/detail4.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail4/detail4-2.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail4/detail4-3.jpg?raw=true',
        ],
        information: {
            상품명: '스컬판다 소리 시리즈',
            브랜드: 'POP MART',
            사용연령: '15세 이상',
            사이즈: '70 ~ 110mm',
            재질: 'PVC / ABS / 자석',
        },
    },
    {
        id: 3,
        title: '디무 꿈나라 시리즈',
        price: '15,000원',
        mainImages: [
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg7/bigImg7-6.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg7/bigImg7-12.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg7/bigImg7-3.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg7/bigImg7-11.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg7/bigImg7-8.jpg?raw=true',
        ],
        detailImages: [
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail7/detail7.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail7/detail7-2.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail7/detail7-3.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail7/detail7-4.jpg?raw=true',
        ],
        information: {
            상품명: '디무 꿈나라 시리즈',
            브랜드: 'POP MART',
            사용연령: '15세 이상',
            사이즈: '70 ~ 110mm',
            재질: 'PVC / ABS',
        },
    },
    {
        id: 4,
        title: '디무 동물의 왕국 시리즈',
        price: '15,000원',
        mainImages: [
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg25/bigImg25-4.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg25/bigImg25-6.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg25/bigImg25-7.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg25/bigImg25-8.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/bigimg/bigImg25/bigImg25-3.jpg?raw=true',
        ],
        detailImages: [
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail25/detail25.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail25/detail25-2.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail25/detail25-3.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail25/detail25-4.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail25/detail25-5.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail25/detail25-6.jpg?raw=true',
            'https://github.com/hyeonky/dp-static/blob/main/popmart/detail/detail25/detail25-7.jpg?raw=true',
        ],
        information: {
            상품명: '디무 동물의 왕국 시리즈',
            브랜드: 'POP MART',
            사용연령: '15세 이상',
            사이즈: '60 ~ 90mm',
            재질: 'PVC / ABS',
        },
    },
];

export default productDetailItem;
